import type { Metadata } from "next";
import { Header } from "@/app/components/organism";

import "./globals.css";

export const metadata: Metadata = {
  title: "Day6",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
